#!/bin/bash

clear

dartanalyzer --options analysis_options.yaml .

echo "# Dart Analyzer Report" >LINT.md
date >>LINT.md
echo "" >>LINT.md
echo "\`\`\`bash" >>LINT.md
dartanalyzer --options analysis_options.yaml . >>LINT.md
echo "\`\`\`" >>LINT.md

pub publish --dry-run
